/** Static instrument catalog — data-only module (no logic). */
export const INSTRUMENTS_DATA = {
    instruments: [
        {
            id: 'BASS',
            midi: [{ name: 'Acoustic Bass', key_based: false }],
            subst: { id1: 'HI_TOM' },
            name: { syn: ['.*BASS.*'] },
            drum: false,
            pan: '0',
        },
        {
            id: 'BONGOS',
            midi: [{ name: 'Hi Bongo', key_based: true }],
            subst: { id1: 'HI_CONGAS', id2: 'CONGAS', id3: 'RIMSHOT' },
            name: { syn: ['.*BNG.*', '.*BONG.*'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'BRASS',
            midi: [{ name: 'Synth Brass 1', key_based: false }],
            subst: { id1: 'SYNTH', id2: 'MELO', id3: 'ORGAN' },
            name: { syn: ['.*BRASS.*', '.*TRUMPET.*', '.*TROMBONE.*', '.*TUBA.*', '.*FRENCH.*HORN.*', '.*HORN.*'] },
            drum: false,
            pan: '0',
        },
        {
            id: 'CABA',
            midi: [{ name: 'Cabasa', key_based: true }],
            subst: { id1: 'HI_CONGAS' },
            name: { syn: ['CABASA'] },
            drum: true,
            pan: '5',
        },
        {
            id: 'CASTENET',
            midi: [{ name: 'Synth Drum', key_based: false }],
            subst: { id1: 'CLAP' },
            name: { syn: ['CAST'] },
            drum: true,
            pan: '8',
        },
        {
            id: 'CLAVES',
            midi: [{ name: 'Claves', key_based: true }],
            subst: { id1: 'RIMSHOT', id2: 'CLAP' },
            name: { syn: ['.*CLAVE.*', '.*CLAV.*'] },
            drum: true,
            pan: '5',
        },
        {
            id: 'OHH',
            midi: [{ name: 'Open Hi-Hat', key_based: true }],
            subst: { id1: 'CHH' },
            name: { syn: ['.*OHAT.*', '.*OHH.*', '.*OHT.*', '.*HHO.*', '.*OPHAT.*', 'OH'], adj_open: 'OPEN' },
            drum: true,
            pan: '-4',
        },
        {
            id: 'CHH',
            midi: [{ name: 'Closed Hi-Hat', key_based: true }],
            subst: { id1: 'SNARE' },
            name: { syn: ['.*HAT.*', '.*CHT.*', '.*HHC.*', 'CHAT', '.*HH.*', '.*CHH.*', 'CH'], adj_open: 'CLOSE' },
            drum: true,
            pan: '2',
        },
        {
            id: 'CHHK',
            midi: [{ name: 'Closed Hi-Hat', key_based: true }],
            subst: { id1: 'CHH' },
            name: { syn: ['PEDAL', 'CPEDAL'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'CHI_CONGAS',
            midi: [{ name: 'Mute Hi Conga', key_based: true }],
            subst: { id1: 'HI_CONGAS' },
            name: { syn: ['.*CLOSEDCONGA.*'], adj_pitch: 'HIGH' },
            drum: true,
            pan: '3',
        },
        {
            id: 'CLAP',
            midi: [{ name: 'Hand Clap', key_based: true }],
            subst: { id1: 'SNARE' },
            name: { syn: ['.*CLAP.*', '.*CLP.*', 'CP', '.*HAND.*', '.*SNAP.*'] },
            drum: true,
            pan: '2',
        },
        {
            id: 'CONGAS',
            midi: [{ name: 'Open Hi Conga', key_based: true }],
            subst: { id1: 'HI_CONGAS', id2: 'HI_TOM', id3: 'TOM' },
            name: { syn: ['.*CON.*', '.*CNG.*', '.*PER.*', 'MC'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'COWBELL',
            midi: [{ name: 'Cowbell', key_based: true }],
            subst: { id1: 'RIDE' },
            name: { syn: ['CB', '.*COW.*', '.*AGOGO.*', '.*BELL.*'] },
            drum: true,
            pan: '2',
        },
        {
            id: 'CRASH',
            midi: [{ name: 'Crash Cymbal 1', key_based: true }],
            subst: { id1: 'CYM' },
            name: { syn: ['.*CYMBAL.*', '.*CYM.*', 'CY', '.*CRASH.*', '.*PLASH.*', '.*CHINA.*', '.*CHOKE.*'] },
            drum: true,
            pan: '-8',
        },
        {
            id: 'CROMAPERC',
            midi: [{ name: 'Marimba', key_based: false }],
            subst: { id1: 'PIANO', id2: 'MELO', id3: 'HI_TOM' },
            name: {
                syn: [
                    '.*CROMA.*',
                    '.*CHROMATIC.*',
                    '.*CELESTA.*',
                    '.*GLOCK.*',
                    '.*MUSIC.*BOX.*',
                    '.*VIBRAPHONE.*',
                    '.*VIBES.*',
                    '.*MARIMBA.*',
                    '.*XYLO.*',
                    '.*TUBULAR.*BELL.*',
                    '.*DULCIMER.*',
                ],
            },
            drum: false,
            pan: '0',
        },
        { id: 'CYM', drum: true, pan: '0', subst: { id1: 'CRASH' } },
        {
            id: 'ENSEMBLE',
            midi: [{ name: 'String Ensemble 1', key_based: false }],
            subst: { id1: 'BRASS', id2: 'PIANO', id3: 'MELO' },
            name: { syn: ['.*ENSEM.*', '.*CHOIR.*', '.*VOIC.*', '.*ORCHESTRA.*HIT.*', '.*ORCH.*HIT.*'] },
            drum: false,
            pan: '0',
        },
        {
            id: 'ETHNIC',
            midi: [{ name: 'Sitar', key_based: false }],
            subst: { id1: 'BASS', id2: 'RIMSHOT', id3: 'HI_TOM' },
            name: {
                syn: [
                    '.*ETHN.*',
                    '.*SITAR.*',
                    '.*BANJO.*',
                    '.*SHAMISEN.*',
                    '.*KOTO.*',
                    '.*KALIMBA.*',
                    '.*BAGPIPE.*',
                    '.*FIDDLE.*',
                    '.*SHANAI.*',
                ],
            },
            drum: false,
            pan: '0',
        },
        {
            id: 'GUITAR',
            midi: [{ name: 'Distortion Guitar', key_based: false }],
            subst: { id1: 'BASS' },
            name: { syn: ['.*GUITAR.*', '.*GTR.*', 'E.GUIT'] },
            drum: false,
            pan: '7',
        },
        {
            id: 'GUIRO',
            midi: [
                { name: 'Short Guiro', key_based: true },
                { name: 'Long Guiro', key_based: true },
            ],
            subst: { id1: 'MARACAS', id2: 'SHAKER' },
            name: { syn: ['.*GUIRO.*', '.*GURO.*'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'CUICA',
            midi: [
                { name: 'Mute Cuica', key_based: true },
                { name: 'Open Cuica', key_based: true },
            ],
            subst: { id1: 'CONGAS', id2: 'HI_TOM' },
            name: { syn: ['.*CUICA.*', '.*CUCA.*'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'HI_BONGOS',
            midi: [{ name: 'Hi Bongo', key_based: true }],
            subst: { id1: 'HI_CONGAS', id2: 'CONGAS', id3: 'RIMSHOT' },
            name: { syn: ['.*HBONGO.*', '.*HIGH.*BONGO.*'], adj_pitch: 'HIGH' },
            drum: true,
            pan: '0',
        },
        {
            id: 'HI_CONGAS',
            midi: [{ name: 'Open Hi Conga', key_based: true }],
            subst: { id1: 'CONGAS', id2: 'HI_TOM', id3: 'TOM' },
            name: { syn: ['.*HCONGA.*', '.*CONGA.*HIGH.*', 'HC'], adj_pitch: 'HIGH' },
            drum: true,
            pan: '3',
        },
        {
            id: 'HI_TIMBAL',
            midi: [{ name: 'High Timbale', key_based: true }],
            subst: { id1: 'SNARE' },
            name: { syn: ['.*HI_TIMBAL.*', '.*HIGH.*TIMBAL.*'] },
            drum: true,
            pan: '8',
        },
        {
            id: 'HI_TOM',
            midi: [{ name: 'High Tom', key_based: true }],
            subst: { id1: 'TOM' },
            name: {
                syn: ['HT', '.*HITOM.*', '.*HTOM.*', '.*TOMH.*', '.*TOM.*HI.*', '.*HI_TOM.*'],
                adj_pitch: 'HIGH',
            },
            drum: true,
            pan: '7',
        },
        {
            id: 'HI_WOODBLOCK',
            midi: [{ name: 'Hi Wood Block', key_based: true }],
            subst: { id1: 'LO_WOODBLOCK', id2: 'RIMSHOT' },
            name: { syn: ['HWOOD'] },
            drum: true,
            pan: '-2',
        },
        {
            id: 'HIT',
            midi: [{ name: 'Synth Drum', key_based: false }],
            subst: { id1: 'SNARE' },
            name: { syn: ['.*BEEP.*', '.*BIP.*', '.*ZAP.*', '.*POP.*', '.*SHOT.*', '.*LASER.*', '.*GUN.*'] },
            drum: true,
            pan: '5',
        },
        {
            id: 'KICK',
            midi: [{ name: 'Bass Drum 1', key_based: true }],
            subst: { id1: 'KICK' },
            name: {
                syn: ['.*KICK.*', '.*KCK.*', '.*KIK.*', 'KD', '.*BD.*', 'ACC.*BD', 'D.*BASS', 'BASS.*DRUM', 'SINUS'],
                adj_height: '',
                adj_open: '',
                adj_style: 'ACCOUSTIC',
            },
            drum: true,
            pan: '0',
        },
        {
            id: 'LO_BONGOS',
            midi: [{ name: 'Low Bongo', key_based: true }],
            subst: { id1: 'SNARE' },
            name: { syn: ['.*LBONGO.*'] },
            drum: true,
            pan: '6',
        },
        {
            id: 'LO_CONGAS',
            midi: [{ name: 'Low Conga', key_based: true }],
            subst: { id1: 'CONGAS', id2: 'LO_TOM', id3: 'TOM' },
            name: { syn: ['LCONGA.*', '.*CONGA.*LOW.*', 'LC'], adj_pitch: 'LOW' },
            drum: true,
            pan: '-3',
        },
        {
            id: 'LO_TIMBAL',
            midi: [{ name: 'Low Timbale', key_based: true }],
            subst: { id1: 'SNARE' },
            name: { syn: ['.*LO_TIMBAL.*', '.*LOW.*TIMBAL.*'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'LO_TOM',
            midi: [
                { name: 'Low Tom', key_based: true },
                { name: 'Low Floor Tom', key_based: true },
            ],
            subst: { id1: 'TOM' },
            name: {
                syn: ['.*LTOM.*', 'LT.*', '.*LOWTOM.*', '.*TOMLOW.*', '.*TOM.*LO.*', '.*LO_TOM.*'],
                adj_pitch: 'LOW',
            },
            drum: true,
            pan: '2',
        },
        {
            id: 'LO_WOODBLOCK',
            midi: [{ name: 'Low Wood Block', key_based: true }],
            subst: { id1: 'RIMSHOT' },
            name: { syn: ['WOOD', 'WOOD BLOCK', 'BLOCK'] },
            drum: true,
            pan: '2',
        },
        {
            id: 'LONGBRASS',
            midi: [{ name: 'Brass Section', key_based: false }],
            subst: { id1: 'SHORTBRASS', id2: 'BRASS', id3: 'MELO' },
            name: { syn: ['.*LONG.*BRASS.*'] },
            drum: false,
            pan: '0',
        },
        {
            id: 'LOOP',
            midi: [{ name: 'Applause', key_based: true }],
            name: { syn: ['.*LOOP.*'] },
            drum: false,
            pan: '0',
        },
        {
            id: 'MARACAS',
            midi: [{ name: 'Maracas', key_based: true }],
            subst: { id1: 'CHH' },
            name: { syn: ['MARA', 'MA', '.*MARACAS?.*', '.*MARACA.*'] },
            drum: true,
            pan: '8',
        },
        {
            id: 'MELO',
            midi: [{ name: 'Percussive Organ', key_based: false }],
            subst: { id1: 'PIANO', id2: 'SYNTH', id3: 'TOM' },
            name: { syn: ['.*MELO.*', '.*MELODIC.*'] },
            drum: false,
            pan: '1',
        },
        {
            id: 'MTOM',
            midi: [{ name: 'Hi-Mid Tom', key_based: true }],
            subst: { id1: 'TOM' },
            name: { syn: ['MTOM.*', 'MT', 'DRUM'], adj_pitch: 'MEDIUM' },
            drum: true,
            pan: '4',
        },
        {
            id: 'OHI_CONGAS',
            midi: [{ name: 'Open Hi Conga', key_based: true }],
            subst: { id1: 'HI_CONGAS' },
            name: { syn: ['.*OHCONGA.*', '.*OPEN.*CONGA.*'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'ORGAN',
            midi: [{ name: 'Drawbar Organ', key_based: false }],
            subst: { id1: 'PIANO', id2: 'MELO', id3: 'HI_TOM' },
            name: { syn: ['.*ORGAN.*', '.*ACCORDION.*', '.*HARMONICA.*', '.*TANGO.*'] },
            drum: false,
            pan: '0',
        },
        {
            id: 'PERC',
            midi: [
                { name: 'High Floor Tom', key_based: true },
                { name: 'High Agogo', key_based: true },
                { name: 'Low Agogo', key_based: true },
                { name: 'Low-Mid Tom', key_based: true },
                { name: 'Long Whistle', key_based: true },
                { name: 'Short Guiro', key_based: true },
                { name: 'Long Guiro', key_based: true },
                { name: 'Claves', key_based: true },
                { name: 'Chinese Cymbal', key_based: true },
                { name: 'Hi Wood Block', key_based: true },
                { name: 'Ride Bell', key_based: true },
                { name: 'Mute Cuica', key_based: true },
                { name: 'Splash Cymbal', key_based: true },
                { name: 'Open Cuica', key_based: true },
                { name: 'Vibraslap', key_based: true },
            ],
            subst: { id1: 'CONGAS' },
            name: { syn: ['.*UNKNOWN.*'] },
            drum: false,
            pan: '0',
        },
        {
            id: 'PERCUSSIVE',
            midi: [{ name: 'Steel Drums', key_based: false }],
            subst: { id1: 'HI_CONGAS', id2: 'HI_TOM', id3: 'RIMSHOT' },
            name: { syn: ['.*PERCUSS.*', '.*STEEL.*DRUM.*', '.*TAIKO.*', '.*MELODIC.*TOM.*', '.*SYNTH.*DRUM.*'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'PIANO',
            midi: [{ name: 'Acoustic Grand Piano', key_based: false }],
            subst: { id1: 'MELO', id2: 'MTOM', id3: 'HI_TOM' },
            name: { syn: ['RHODE', '.*PIANO.*', '.*GRAND.*', '.*HONKY.*', '.*HARPSICHORD.*', '.*CLAVINET.*'] },
            drum: false,
            pan: '0',
        },
        {
            id: 'PIPE',
            midi: [{ name: 'Flute', key_based: false }],
            subst: { id1: 'PIANO', id2: 'MELO', id3: 'HI_TOM' },
            name: {
                syn: [
                    '.*PIPE.*',
                    '.*FLUTE.*',
                    '.*PICCOLO.*',
                    '.*RECORDER.*',
                    '.*PAN.*FLUTE.*',
                    '.*PANFLUTE.*',
                    '.*SHAKUHACHI.*',
                    '.*OCARINA.*',
                    '.*BLOWN.*BOTTLE.*',
                ],
            },
            drum: false,
            pan: '0',
        },
        {
            id: 'RAZOR',
            midi: [{ name: 'Gunshot', key_based: true }],
            subst: { id1: 'HIT' },
            name: { syn: ['RAZ', '.*RAZOR.*'] },
            drum: true,
            pan: '5',
        },
        {
            id: 'REED',
            midi: [{ name: 'Oboe', key_based: false }],
            subst: { id1: 'PIANO', id2: 'MELO', id3: 'HI_TOM' },
            name: { syn: ['.*REED.*', '.*OBOE.*', '.*CLARINET.*', '.*BASSOON.*', '.*ENGLISH.*HORN.*'] },
            drum: false,
            pan: '0',
        },
        {
            id: 'RIDE',
            midi: [{ name: 'Ride Cymbal 1', key_based: true }],
            subst: { id1: 'CYM', id2: 'CHH' },
            name: { syn: ['.*RID.*'] },
            drum: true,
            pan: '7',
        },
        {
            id: 'RIMSHOT',
            midi: [{ name: 'Side Stick', key_based: true }],
            subst: { id1: 'SNARE' },
            name: {
                syn: [
                    '.*RIM.*',
                    '.*WOOD.*',
                    'WOOD BLOCK',
                    'WOODBLOCK',
                    'BLOCK',
                    'STICK',
                    'STIK',
                    'CLI.*',
                    'CL',
                    '.*STICK.*',
                    '.*SIDE.*',
                    '.*RS.*',
                ],
            },
            drum: true,
            pan: '-2',
        },
        {
            id: 'SAX',
            midi: [{ name: 'Soprano Sax', key_based: false }],
            subst: { id1: 'PIANO' },
            name: { syn: ['saxophone', 'saxo', '.*SAX.*'] },
            drum: false,
            pan: '7',
        },
        {
            id: 'SCRATCH',
            midi: [{ name: 'Reverse Cymbal', key_based: false }],
            subst: { id1: 'SOUNDEFFECT', id2: 'HIT', id3: 'CRASH' },
            name: { syn: ['.*SCRATCH.*'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'SHAKER',
            midi: [{ name: 'Maracas', key_based: true }],
            subst: { id1: 'MARACAS', id2: 'RIMSHOT', id3: 'COWBELL' },
            name: { syn: ['.*SHAKE.*', '.*SHACK.*'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'SHORTBRASS',
            midi: [{ name: 'Synth Brass 2', key_based: false }],
            subst: { id1: 'LONGBRASS', id2: 'BRASS', id3: 'MELO' },
            name: { syn: ['.*SHORT.*BRASS.*'] },
            drum: false,
            pan: '0',
        },
        {
            id: 'SNARE',
            midi: [
                { name: 'Acoustic Snare', key_based: true },
                { name: 'Electric Snare', key_based: true },
            ],
            subst: { id1: 'SNARE' },
            name: {
                syn: ['SN', '.*SNAR.*', '.*SD.*', 'SN', 'SNR', 'ACC AC', 'AC', '.*BRUSH.*'],
                adj_style: 'ACCOUSTIC',
            },
            drum: true,
            pan: '3',
        },
        {
            id: 'SOUNDEFFECT',
            midi: [{ name: 'Seashore', key_based: true }],
            subst: { id1: 'CRASH', id2: 'HIT', id3: 'SCRATCH' },
            name: {
                syn: [
                    '.*FX.*',
                    '.*SOUND.*',
                    '.*SND.*',
                    '.*VINYL.*',
                    '.*CRACKL.*',
                    '.*RISER.*',
                    '.*IMPACT.*',
                    '.*DOWNLIFT.*',
                    '.*FOLEY.*',
                    '.*SEASHORE.*',
                    '.*BIRD.*',
                    '.*APPLAUSE.*',
                    '.*HELICOPTER.*',
                    '.*TELEPHONE.*',
                    '.*GUNSHOT.*',
                    '.*REVERSE.*',
                    '.*BREATH.*',
                    '.*FRET.*NOISE.*',
                    '.*RAIN.*',
                    '.*SOUNDTRACK.*',
                    '.*CRYSTAL.*',
                    '.*ATMOS.*',
                    '.*BRIGHT.*',
                    '.*GOBLIN.*',
                    '.*ECHO.*',
                    '.*SCI.*FI.*',
                ],
            },
            drum: true,
            pan: '0',
        },
        {
            id: 'STRINGS',
            midi: [{ name: 'String Ensemble 1', key_based: false }],
            subst: { id1: 'BRASS', id2: 'PIANO', id3: 'MELO' },
            name: {
                syn: [
                    '.*STRING.*',
                    '.*VIOLIN.*',
                    '.*VIOLA.*',
                    '.*CELLO.*',
                    '.*CONTRABASS.*',
                    '.*HARP.*',
                    '.*TIMPANI.*',
                    '.*PIZZICATO.*',
                    '.*TREMOLO.*',
                ],
            },
            drum: false,
            pan: '0',
        },
        { id: 'SYNTH', drum: false, pan: '0', subst: { id1: 'MELO' } },
        {
            id: 'SYNTHEFFECT',
            midi: [{ name: 'Reverse Cymbal', key_based: false }],
            subst: { id1: 'HIT', id2: 'CRASH', id3: 'RIMSHOT' },
            name: { syn: ['.*SYNTH.*EFFECT.*', '.*FX.*'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'SYNTHLEAD',
            midi: [{ name: 'Lead 1 (square)', key_based: false }],
            subst: { id1: 'PIANO', id2: 'MELO', id3: 'HI_TOM' },
            name: {
                syn: [
                    '.*SYNTH.*',
                    '.*LEAD.*',
                    '.*SQUARE.*',
                    '.*SAW.*',
                    '.*CALLIOPE.*',
                    '.*CHIFF.*',
                    '.*CHARANG.*',
                    '.*FIFTHS.*',
                ],
            },
            drum: false,
            pan: '0',
        },
        {
            id: 'SYNTHPAD',
            midi: [{ name: 'Pad 1 (new age)', key_based: false }],
            subst: { id1: 'HIT', id2: 'CRASH', id3: 'RIMSHOT' },
            name: {
                syn: [
                    '.*SYNTH.*PAD.*',
                    '.*PAD.*',
                    '.*NEW.*AGE.*',
                    '.*WARM.*',
                    '.*BOWED.*',
                    '.*METALLIC.*',
                    '.*HALO.*',
                    '.*SWEEP.*',
                ],
            },
            drum: false,
            pan: '0',
        },
        {
            id: 'TAMB',
            midi: [{ name: 'Tambourine', key_based: true }],
            subst: { id1: 'SNARE', id2: 'HI_TOM', id3: 'CHH' },
            name: { syn: ['.*TAMB.*'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'TAMBOURINE',
            midi: [{ name: 'Tambourine', key_based: true }],
            subst: { id1: 'OHH' },
            name: { syn: ['.*TAMB.*'] },
            drum: true,
            pan: '-2',
        },
        {
            id: 'TIMBAL',
            midi: [{ name: 'High Timbale', key_based: true }],
            subst: { id1: 'LO_TOM', id2: 'CRASH', id3: 'SNARE' },
            name: { syn: ['.*TIMBAL.*', 'TIMBALE'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'TOM',
            midi: [{ name: 'Hi-Mid Tom', key_based: true }],
            subst: { id1: 'HI_TOM', id2: 'MTOM', id3: 'CHH' },
            name: { syn: ['.*TOM.*'] },
            drum: true,
            pan: '2',
        },
        {
            id: 'TRIANGLE',
            midi: [
                { name: 'Open Triangle', key_based: true },
                { name: 'Mute Triangle', key_based: true },
            ],
            subst: { id1: 'TAMBOURINE', id2: 'RIMSHOT', id3: 'SNARE' },
            name: { syn: ['.*TRI.*'] },
            drum: true,
            pan: '5',
        },
        {
            id: 'VIBRA',
            midi: [{ name: 'Vibraslap', key_based: true }],
            subst: { id1: 'HIT', id2: 'CRASH', id3: 'RIMSHOT' },
            name: { syn: ['.*VIBRA.*'] },
            drum: true,
            pan: '0',
        },
        {
            id: 'WHISTLE',
            midi: [{ name: 'Short Whistle', key_based: true }],
            subst: { id1: 'MARACAS', id2: 'RIMSHOT', id3: 'HIT' },
            name: { syn: ['.*WHISTL.*'] },
            drum: true,
            pan: '0',
        },
    ],
}
