let MfGlobals = {
    sounds: [],
    scales: {},
    generatedSounds :{},
    patterns:[
         {
        "name": "rock",
        "tags": {
            "style": "rock",
            "type": "default"
        },
        "tracks": [
            {
                "name": "KICK",
                "autoSound": true,
                "soundNum": 0,
                "bars": 8,
                "nbStepPerBar": 4,
                "loopPoint": 32,
                "swingRez": 1,
                "swingDepth": 0,
                "velo": 0.5,
                "veloLfo": null,
                "pitch": 0,
                "pitchLfo": null,
                "pano": 0,
                "panoLfo": null,
                "solo": false,
                "mute": false,
                "auto": false,
                "notes": [
                    {
                        "name": "N_KICK_0",
                        "step": 0,
                        "bar": 0,
                        "velo": 1,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "steppc": 0,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_KICK_8",
                        "step": 0,
                        "bar": 2,
                        "velo": 1,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "steppc": 0,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_KICK_10",
                        "step": 2,
                        "bar": 2,
                        "velo": 1,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "steppc": 50,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_KICK_14",
                        "step": 2,
                        "bar": 3,
                        "velo": 0.5,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 4,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "steppc": 50,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_KICK_4_0",
                        "step": 0,
                        "steppc": 0,
                        "bar": 4,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_KICK_4_2",
                        "step": 2,
                        "steppc": 50,
                        "bar": 4,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_KICK_5_2",
                        "step": 2,
                        "steppc": 50,
                        "bar": 5,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_KICK_6_2",
                        "step": 2,
                        "steppc": 50,
                        "bar": 6,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    }
                ],
                "loopPointBar": 8,
                "loopPointStep": 0,
                "generated": false,
                "filterType": "allpass",
                "filterFreq": 0,
                "filterQ": 0,
                "filterFreqLfo": null,
                "filterQLfo": null,
                "filterLfoFreq": 0,
                "sampleLength": 1
            },
            {
                "name": "SNARE",
                "autoSound": true,
                "soundNum": 1,
                "bars": 8,
                "nbStepPerBar": 4,
                "loopPoint": 32,
                "swingRez": 1,
                "swingDepth": 0,
                "velo": 1,
                "veloLfo": null,
                "pitch": 0,
                "pitchLfo": null,
                "pano": 0.3,
                "panoLfo": null,
                "solo": false,
                "mute": false,
                "notes": [
                    {
                        "name": "N_SNARE_4",
                        "step": 0,
                        "bar": 1,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "steppc": 0,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_SNARE_7",
                        "step": 3,
                        "bar": 1,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 4,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "steppc": 75,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_SNARE_9",
                        "step": 1,
                        "bar": 2,
                        "velo": 1,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 4,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "steppc": 25,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_SNARE_12",
                        "step": 0,
                        "bar": 3,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "steppc": 0,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_SNARE_5_0",
                        "step": 0,
                        "steppc": 0,
                        "bar": 5,
                        "velo": 1,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_SNARE_7_0",
                        "step": 0,
                        "steppc": 0,
                        "bar": 7,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_SNARE_7_1",
                        "step": 1,
                        "steppc": 25,
                        "bar": 7,
                        "velo": 0.3,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 4,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_SNARE_7_2",
                        "step": 2,
                        "steppc": 50,
                        "bar": 7,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 3,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_SNARE_7_3",
                        "step": 3,
                        "steppc": 75,
                        "bar": 7,
                        "velo": 0.3,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 4,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    }
                ],
                "loopPointBar": 8,
                "loopPointStep": 0,
                "generated": false,
                "filterType": "allpass",
                "filterFreq": 0,
                "filterQ": 0,
                "filterFreqLfo": null,
                "filterQLfo": null,
                "filterLfoFreq": 0,
                "sampleLength": 1
            },
            {
                "name": "TOM",
                "autoSound": true,
                "soundNum": 4,
                "bars": 8,
                "nbStepPerBar": 4,
                "loopPoint": 32,
                "swingRez": 1,
                "swingDepth": 0,
                "velo": 1,
                "veloLfo": null,
                "pitch": 0,
                "pitchLfo": null,
                "pano": 0.5,
                "panoLfo": null,
                "solo": false,
                "mute": false,
                "notes": [
                    {
                        "name": "N_TOM_6_0",
                        "step": 0,
                        "steppc": 0,
                        "bar": 6,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 6,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    }
                ],
                "loopPointBar": 8,
                "loopPointStep": 0,
                "generated": false,
                "filterType": "allpass",
                "filterFreq": 0,
                "filterQ": 0,
                "filterFreqLfo": null,
                "filterQLfo": null,
                "filterLfoFreq": 0,
                "sampleLength": 1
            },
            {
                "name": "CLAP",
                "autoSound": true,
                "soundNum": 5,
                "bars": 8,
                "nbStepPerBar": 4,
                "loopPoint": 32,
                "swingRez": 1,
                "swingDepth": 0.3,
                "velo": 1,
                "veloLfo": null,
                "pitch": 0,
                "pitchLfo": null,
                "pano": -0.4,
                "panoLfo": {
                    "name": "panoTrack",
                    "wave": 1,
                    "freq": 1,
                    "freqMulpt": 6,
                    "min": 0,
                    "max": 1,
                    "phase": 0
                },
                "solo": false,
                "mute": false,
                "notes": [
                    {
                        "name": "N_CLAP_3_0",
                        "step": 0,
                        "steppc": 0,
                        "bar": 3,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 16,
                        "triggPhase": 8,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_CLAP_3_1",
                        "step": 1,
                        "steppc": 25,
                        "bar": 3,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 16,
                        "triggPhase": 8,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_CLAP_3_2",
                        "step": 2,
                        "steppc": 50,
                        "bar": 3,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 16,
                        "triggPhase": 8,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_CLAP_3_3",
                        "step": 3,
                        "steppc": 75,
                        "bar": 3,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 16,
                        "triggPhase": 8,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    }
                ],
                "loopPointBar": 8,
                "loopPointStep": 0,
                "generated": false,
                "filterType": "allpass",
                "filterFreq": 0,
                "filterQ": 0,
                "filterFreqLfo": null,
                "filterQLfo": null,
                "filterLfoFreq": 0,
                "sampleLength": 1
            },
            {
                "name": "COW",
                "autoSound": true,
                "soundNum": 4,
                "bars": 8,
                "nbStepPerBar": 4,
                "loopPoint": 4,
                "swingRez": 1,
                "swingDepth": 0,
                "velo": 0.3,
                "veloLfo": null,
                "pitch": 0,
                "pitchLfo": null,
                "pano": 0.4,
                "panoLfo": null,
                "solo": false,
                "mute": false,
                "notes": [
                    {
                        "name": "N_COW_0_0",
                        "step": 0,
                        "steppc": 0,
                        "bar": 0,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 16,
                        "triggPhase": 6,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_COW_4_0",
                        "step": 0,
                        "steppc": 0,
                        "bar": 4,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 3,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_COW_0_2",
                        "step": 2,
                        "steppc": 50,
                        "bar": 0,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 16,
                        "triggPhase": 6,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    }
                ],
                "loopPointBar": 1,
                "loopPointStep": 0,
                "generated": false,
                "filterType": "allpass",
                "filterFreq": 0,
                "filterQ": 0,
                "filterFreqLfo": null,
                "filterQLfo": null,
                "filterLfoFreq": 0,
                "sampleLength": 1
            },
            {
                "name": "CHH",
                "autoSound": true,
                "soundNum": 3,
                "bars": 8,
                "nbStepPerBar": 4,
                "loopPoint": 4,
                "swingRez": 1,
                "swingDepth": 0.2,
                "velo": 0.3,
                "veloLfo": {
                    "name": "volTrack",
                    "wave": 1,
                    "freq": 5,
                    "freqMulpt": 1,
                    "min": 0.1,
                    "max": 0.4,
                    "phase": 0
                },
                "pitch": 0,
                "pitchLfo": null,
                "pano": -0.3,
                "panoLfo": null,
                "solo": false,
                "mute": false,
                "notes": [
                    {
                        "name": "N_CHH_0",
                        "step": 0,
                        "bar": 0,
                        "velo": 1,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "steppc": 0,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_CHH_1",
                        "step": 1,
                        "bar": 0,
                        "velo": 0.6,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "steppc": 25,
                        "euclidianFill": 0
                    },
                    {
                        "name": "N_CHH_0_3",
                        "step": 3,
                        "steppc": 75,
                        "bar": 0,
                        "velo": 0.8,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "euclidianFill": 0
                    }
                ],
                "loopPointBar": 1,
                "loopPointStep": 0,
                "generated": false,
                "filterType": "allpass",
                "filterFreq": 0,
                "filterQ": 0,
                "filterFreqLfo": null,
                "filterQLfo": null,
                "filterLfoFreq": 0,
                "sampleLength": 1
            },
            {
                "name": "OHH",
                "autoSound": true,
                "soundNum": 4,
                "bars": 8,
                "nbStepPerBar": 4,
                "loopPoint": 4,
                "swingRez": 1,
                "swingDepth": 0,
                "velo": 0.9,
                "veloLfo": null,
                "pitch": 0,
                "pitchLfo": null,
                "pano": -0.2,
                "panoLfo": {
                    "name": "panoTrack",
                    "wave": 1,
                    "freq": 1,
                    "freqMulpt": 1,
                    "min": 0.3,
                    "max": 0.7,
                    "phase": 0
                },
                "solo": false,
                "mute": false,
                "notes": [
                    {
                        "name": "N_OHH_2",
                        "step": 2,
                        "bar": 0,
                        "velo": 1,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 1,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "steppc": 50,
                        "euclidianFill": 0
                    }
                ],
                "loopPointBar": 1,
                "loopPointStep": 0,
                "generated": false,
                "filterType": "allpass",
                "filterFreq": 0,
                "filterQ": 0,
                "filterFreqLfo": null,
                "filterQLfo": null,
                "filterLfoFreq": 0,
                "sampleLength": 1
            },
            {
                "name": "CRASH",
                "autoSound": true,
                "soundNum": 7,
                "bars": 8,
                "nbStepPerBar": 4,
                "loopPoint": 32,
                "swingRez": 1,
                "swingDepth": 0,
                "velo": 1,
                "veloLfo": null,
                "pitch": 0,
                "pitchLfo": null,
                "pano": 1,
                "panoLfo": null,
                "solo": false,
                "mute": false,
                "notes": [
                    {
                        "name": "N_CRASH_0",
                        "step": 0,
                        "bar": 0,
                        "velo": 1,
                        "pano": 0,
                        "pitch": 0,
                        "arp": null,
                        "triggFreq": 4,
                        "triggPhase": 0,
                        "retriggNum": 1,
                        "retriggStep": 1,
                        "retriggStepMulpt": 1,
                        "steppc": 0,
                        "euclidianFill": 0
                    }
                ],
                "loopPointBar": 8,
                "loopPointStep": 0,
                "generated": false,
                "filterType": "allpass",
                "filterFreq": 0,
                "filterQ": 0,
                "filterFreqLfo": null,
                "filterQLfo": null,
                "filterLfoFreq": 0,
                "sampleLength": 1
            }
        ],
        "bpm": 120,
        "nbBars": 8,
        "application": "online-ordrumbox",
        "url": "https://www.ordrumbox.com"
    }
    ],
    drumkitList:[
         {
        "name": "real",
        "infos": "@9mattyeux kit",
        "desc": "recorded by mweb in the studio",
        "instruments": [
            {
                "display_name": "kick.wav",
                "key": "KICK",
                "url": "real/kick.wav"
            },
            {
                "display_name": "snare.wav",
                "key": "SNARE",
                "url": "real/snare.wav"
            },
            {
                "display_name": "tom.wav",
                "key": "TOM",
                "url": "real/tom.wav"
            },
            {
                "display_name": "rimshot.wav",
                "key": "CLAP",
                "url": "real/rim.wav"
            },
            {
                "display_name": "cow.wav",
                "key": "COW",
                "url": "real/cow.wav"
            },
            {
                "display_name": "chh.wav",
                "key": "CHH",
                "url": "real/chh.wav"
            },
            {
                "display_name": "ohh.wav",
                "key": "OHH",
                "url": "real/ohh.wav"
            },
            {
                "display_name": "crash.wav",
                "key": "CRASH",
                "url": "real/crash.wav"
            }
        ]
    }
    ],
    trackLib:[],
    drumkits:{},
    leds:{},
    blob:null,
    audioCtx: null,
    secondsPerBeat:8,  //i.e BPM
    selectedDrumkit: "real",
    selectedDrumkitNum: 0,
    selectedPatternNum: 0,
    selectedTrackNum:0,
    selectedLfo:"pitchLfo",
    displayBars:1, //current displayBar
    mfPatterns:null,  // can compute flatnotes
    mfUpdates:null,  // mvc (v)
    mfMixer:null,
    TICK : 32,  // bar internal division
    autoMode:false,  // bass generation
    textInput:false     //beurk TODO
}