export const playbackEvents = {
    onPlaybackStart: [],
    onPlaybackStop: [],
    onPatternChange: [],
    onDrumkitChange: [],
    onBpmChange: [],
    onNoteSelect: [],
    onTrackSelect: [],
    onTrackParamChange: [],
    onToolsToggle: [],
    onOutputToggle: [],
    onAboutToggle: [],
    onWorkletStatusChange: [],
    onLoopPointChange: [],
    onNoteTrigger: [],
    onStall: [],
    onStallResume: [],
    onDrumkitManagerToggle: [],

    offPlaybackStart(fn) { this.onPlaybackStart = this.onPlaybackStart.filter(f => f !== fn) },
    offPlaybackStop(fn) { this.onPlaybackStop = this.onPlaybackStop.filter(f => f !== fn) },
    offPatternChange(fn) { this.onPatternChange = this.onPatternChange.filter(f => f !== fn) },
    offDrumkitChange(fn) { this.onDrumkitChange = this.onDrumkitChange.filter(f => f !== fn) },
    offBpmChange(fn) { this.onBpmChange = this.onBpmChange.filter(f => f !== fn) },
    offNoteSelect(fn) { this.onNoteSelect = this.onNoteSelect.filter(f => f !== fn) },
    offTrackSelect(fn) { this.onTrackSelect = this.onTrackSelect.filter(f => f !== fn) },
    offTrackParamChange(fn) { this.onTrackParamChange = this.onTrackParamChange.filter(f => f !== fn) },
    offToolsToggle(fn) { this.onToolsToggle = this.onToolsToggle.filter(f => f !== fn) },
    offOutputToggle(fn) { this.onOutputToggle = this.onOutputToggle.filter(f => f !== fn) },
    offAboutToggle(fn) { this.onAboutToggle = this.onAboutToggle.filter(f => f !== fn) },
    offWorkletStatusChange(fn) { this.onWorkletStatusChange = this.onWorkletStatusChange.filter(f => f !== fn) },
    offLoopPointChange(fn) { this.onLoopPointChange = this.onLoopPointChange.filter(f => f !== fn) },
    offNoteTrigger(fn) { this.onNoteTrigger = this.onNoteTrigger.filter(f => f !== fn) },
    offStall(fn) { this.onStall = this.onStall.filter(f => f !== fn) },
    offStallResume(fn) { this.onStallResume = this.onStallResume.filter(f => f !== fn) },
    offDrumkitManagerToggle(fn) { this.onDrumkitManagerToggle = this.onDrumkitManagerToggle.filter(f => f !== fn) },

    dispatchPlaybackStart() { this.onPlaybackStart.forEach(fn => fn()) },
    dispatchPlaybackStop() { this.onPlaybackStop.forEach(fn => fn()) },
    dispatchPatternChange(changedTracks) { this.onPatternChange.forEach(fn => fn(changedTracks)) },
    dispatchDrumkitChange() { this.onDrumkitChange.forEach(fn => fn()) },
    dispatchBpmChange(bpm) { this.onBpmChange.forEach(fn => fn(bpm)) },
    dispatchNoteSelect(data) { this.onNoteSelect.forEach(fn => fn(data)) },
    dispatchTrackSelect(data) { this.onTrackSelect.forEach(fn => fn(data)) },
    dispatchTrackParamChange(track) { this.onTrackParamChange.forEach(fn => fn(track)) },
    dispatchToolsToggle(show) { this.onToolsToggle.forEach(fn => fn(show)) },
    dispatchOutputToggle(show) { this.onOutputToggle.forEach(fn => fn(show)) },
    dispatchAboutToggle(show) { this.onAboutToggle.forEach(fn => fn(show)) },
    dispatchWorkletStatusChange(status) { this.onWorkletStatusChange.forEach(fn => fn(status)) },
    dispatchLoopPointChange(data) { this.onLoopPointChange.forEach(fn => fn(data)) },
    dispatchNoteTrigger(data) { this.onNoteTrigger.forEach(fn => fn(data)) },
    dispatchStall(data) { this.onStall.forEach(fn => fn(data)) },
    dispatchStallResume() { this.onStallResume.forEach(fn => fn()) },
    dispatchDrumkitManagerToggle(show) { this.onDrumkitManagerToggle.forEach(fn => fn(show)) }
}
